default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'postgres' } %>
  port: 5432
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: garcon-net_dev
test:
  <<: *default
  database: garcon-net_test

production:
  <<: *default
  database: garcon-net_prod
